### ISSUE TITLE
Why the output it is limited to 1MB?

### ISSUE THREAD

**Issue by facundofarias** [jingweno/jqplay#40]
Trying to do some operations on a given JSON, I am getting this: 
```
JSON payload size is 1.6MB, larger than limit 1MB.
```
Why is it?

**Comment by nicowilliams** [comment]
(Speaking for myself, not the jqplay team.)  It's a playground.  If you
need to process large amounts of data you should download jq and do it
locally.

**Comment by jingweno** [comment]
@facundofarias: Yes, @nicowilliams was right. Please [download](http://stedolan.github.io/jq/) `jq` if you want to run against larger amounts of data. `jqplay` runs `jq` on each request so it's to make sure request doesn't timeout by constraining data size and execution time.

Closing. Feel free to reopen if you have more questions.

**Comment by facundofarias** [comment]
At least it could be documented, isn't it!?

**Comment by nicowilliams** [comment]
Again, speaking for myself, the service's name denies that it's a
playground.  You can play.  Using the jq executable (or building your own)
is easy enough.  :)
