### ISSUE TITLE
Share jq result

### ISSUE THREAD

**Issue by jingweno** [jingweno/jqplay#8]
It'd be nice to share jqplay result with others

**Comment by jmatsushita** [comment]
This would be fantastic. I'm sure there are some pearls of jq usage out there that deserve to be shared.

**Comment by jmatsushita** [comment]
Maybe some of the [code of the json-ld playground](https://github.com/json-ld/json-ld.org/blob/master/playground/playground.js) (Gist button to Load and Create) would be reusable? http://json-ld.org/playground/

![image](https://cloud.githubusercontent.com/assets/356097/7533407/7c78825e-f571-11e4-8170-750d69d3f6c5.png)

**Comment by jingweno** [comment]
@jmatsushita :+1: Looking good!

**Comment by alexylem** [comment]
So no plan to include the JSON sample? Could be handy so save sessions (even locally) for future usage / finetuning.

**Comment by jingweno** [comment]
@alexylem I really hope this would happen. But couldn't find time to look into. You're welcome to contribute :)

**Comment by mandric** [comment]
Any updates here?  Wondering best way to share a jqplay url that preloads the JSON and filter code.

**Comment by alexylem** [comment]
Fantastic, thanks a lot! 👍
